name: Essential Test

on: workflow_call

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Lint
        run: npx nx lint ngx-deploy-npm

      - name: Lint report
        run: npx nx lint-report ngx-deploy-npm

      - name: Archive lint report results
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: reports

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - run: npx nx build ngx-deploy-npm

      - name: Archive build result
        uses: actions/upload-artifact@v4
        with:
          name: library-dist
          path: dist

  unit-test:
    strategy:
      matrix:
        os: [ubuntu-latest] # to have test faster
        # os: [ubuntu-latest, windows-latest]
        node-version: [20, 22]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}

      - run: npx nx test ngx-deploy-npm --configuration="ci"

      - name: Set Node.js version based on .nvmrc
        shell: bash
        run: |
          version=$(cat .nvmrc)
          echo "Setting default value for node-version parameter: $version"
          echo "NODE_VERSION=$version" >> $GITHUB_ENV
          echo "$NODE_VERSION"

      - if: ${{ matrix.os == 'ubuntu-latest' && matrix.node-version == env.NODE_VERSION }}
        name: Archive coverage report
        uses: actions/upload-artifact@v4
        with:
          name: ngx-deploy-npm-coverage-report
          path: coverage/packages/ngx-deploy-npm/lcov.info
